####################################################
#web访问端口号 约定：80
####################################################
server:
  port: 80

####################################################
#配置数据源信息
####################################################
spring:
  datasource:                                         # 数据源的相关配置
    url:  jdbc:mysql://192.168.13.129:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: 123456